# Generated by Django 4.1 on 2022-08-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_profilr_pic_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('personal seller', 'Personal Seller'), ('business', 'Business')], max_length=256, null=True),
        ),
    ]
